app = "jfkarena-api"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  working_dir = "/app"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # 禁用自动停止
  auto_start_machines = true
  min_machines_running = 1     # 最少运行一台实例
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 